# -*- coding: utf-8-unix -*-

build:
	nativefier \
	--name fastmail \
	--icon fastmail.png \
	--inject fastmail.css \
	--single-instance \
	--electron-version 4.2.11 \
	"https://www.fastmail.com/mail/Inbox/?domain=fastmail.fm" \
	..

.PHONY: build
