# -*- coding: utf-8-unix -*-

build:
	nativefier \
	--name=fastmail \
	--icon=fastmail.png \
	--width=1200 \
	--height=800 \
	--inject=fastmail.css \
	--single-instance \
	"https://www.fastmail.com/mail/Inbox/" \
	..

.PHONY: build
