# -*- coding: utf-8-unix -*-

build:
	nativefier \
	--name dropbox-paper \
	--icon dropbox-paper.png \
	--inject dropbox-paper.css \
	--inject dropbox-paper.js \
	--single-instance \
	"https://paper.dropbox.com/" \
	..

.PHONY: build
