# -*- coding: utf-8-unix -*-

build:
	nativefier \
	--name=gmail \
	--icon=gmail.png \
	--width=1200 \
	--height=800 \
	--single-instance \
	"https://mail.google.com/mail/u/0/#inbox" \
	..

.PHONY: build
